### PR TITLE
Improve performace of EXTRACT operator

### PR DESCRIPTION
**Pull request by testhound**

### CODE REVIEW

**Comment by testhound** [comment]
Wamsi can you be more specific about the GPU side integration?

**Comment by wamsiv** [comment]
@testhound Need to add functions to gpu codegen [QueryEngine/NativeCodegen.cpp](https://github.com/mapd/mapd-core-internal/blob/master/QueryEngine/NativeCodegen.cpp#L349-L352), also need to make adjustments to [QueryEngine/ExpressionRange.cpp](https://github.com/mapd/mapd-core-internal/blob/master/QueryEngine/ExpressionRange.cpp#L777-L781) and [ParserNode.cpp](https://github.com/mapd/mapd-core-internal/blob/master/Parser/ParserNode.cpp#L1024-L1026).

Hope this helps!

**Comment by sashkiani** [comment]
Overall, it looks good. But as @wamsiv also mentioned, at least for this code to work on the GPU too, you'll need to add deceleration for all these new functions in the `QueryEngine/NativeCodegen.cpp`

**Comment by testhound** [comment]
I made all the requested changes for gpu integration and created a new 
pull request.

**Comment by randyzwitch** [comment]
Closing this one as well, I think the two PRs were linked @testhound? If not, we can always reopen

**Pull request closed without merging**
