### PR TITLE
[WIP] Upgrade to Apache Arrow >= 0.8.0 API 

### PR DESCRIPTION
**Pull request by wesm**
I ran into some build problems in https://github.com/mapd/mapd-core/issues/198 and am not able to build the whole project yet. I will be happy to complete this once that is resolved

### CODE REVIEW

**Comment by andrewseidl** [comment]
Do you see any issues with adding an `#ifdef` to keep 0.7.x compatibility around temporarily (and maybe warn as deprecated)? Simply so that we don't have to force everyone to upgrade their dev envs immediately.

Last I looked it didn't seem like Arrow exposed its version in the headers, so we could instead either attempt to pick up the version through pkg-config, or (preferably) do a cmake `try_compile()` to decide which one to use (or maybe `CheckCXXSymbolExists`).

Should be quick, I can take care of it hopefully today.

**Comment by wesm** [comment]
Applications using 0.8.0 are binary-incompatible with <= 0.7.1, so there's only so much benefit to maintaining the old APIs.

**Comment by randyzwitch** [comment]
@andrewseidl Is this something that will make it in soon? Binary incompatibility is making development weird

**Comment by wesm** [comment]
Upgrading should not be difficult. I don't have the bandwidth to steward through a patch right now; if someone can take it over, building the project from source and running the tests is the hardest part

**Comment by randyzwitch** [comment]
Thanks @andrewseidl, let me know what I can do to help if needed

**Pull request closed without merging**
