### PR TITLE
Determine java executable path at cmake configuration.

### PR DESCRIPTION
**Pull request by pearu**
Resolves issue #315 .

### CODE REVIEW

**Comment by pearu** [comment]
@randyzwitch please review.

**Comment by andrewseidl** [comment]
Instead of setting the path at compile time (which is problematic if you build on one machine but try to run on another), could we maybe use `execlp` instead of `execl` and then just tell it to run whatever `java` is in your `PATH`?

**Comment by pearu** [comment]
@andrewseidl , I have switched to using `execlp` that determines the `java` executable at server start.

**Comment by andrewseidl** [comment]
Code looks fine, I need to make sure it doesn't break anything in a few envs.

**Comment by andrewseidl** [comment]
Looks good from my testing on Arch, CentOS 7, and Ubuntu 18.04. Just waiting on some comments internally before merging.

**Comment by pearu** [comment]
Although, the latest mapd-core (v 4.5.0) is released after merging this PR, the PR content is not included in v 4.5.0.

**Pull request merged**
