### PR TITLE
Using parenthesis for print

### PR DESCRIPTION
**Pull request by xmnlab**
In this PR

- added parenthesis for `print` in python code to work on python3

### CODE REVIEW

**Comment by xmnlab** [comment]
not sure why core-clang-format-pr is pointing changes I didn't do.
also I am working with the latest changes on master.

**Comment by andrewseidl** [comment]
@mapd-bot-os retest this please

**Comment by andrewseidl** [comment]
Yeah, that job checks everything, not just changes you made. Had some unformatted changes land in master (fixed now).

**Comment by xmnlab** [comment]
thanks @andrewseidl !

**Pull request merged**
