### PR TITLE
Improve performance of extract operator version 2

### PR DESCRIPTION
**Pull request by testhound**
Merges both sets of changes from mkc_extractfromtime

### CODE REVIEW

**Comment by wamsiv** [comment]
Here are few results of avg benchmark times before and after the patch:

Before (on master):
```
query 1: 2934.9
query 2: 284.6
```

After the patch:

```
query 1: 2439.4
query 2: 265.2
```

**Comment by wamsiv** [comment]
IR for two queries used in bench marks:

On master:

```
mapdql> explain select dest_name, extract(month from dep_timestamp) as m, extract(year from dep_timestamp) as y,   avg(arrdelay) as del from flights group by dest_name,y,m;
Explanation
IR for the CPU:
===============

; Function Attrs: uwtable
define void @query_group_by_template(i8** nocapture readnone %byte_stream, i8* nocapture readonly %literals, i64* nocapture readnone %row_count_ptr, i64* nocapture readonly %frag_row_off_ptr, i32* %max_matched_ptr, i64* %agg_init_val, i64** %group_by_buffers, i64** %small_groups_buffer, i32 %frag_idx, i64* %join_hash_tables, i32* %total_matched, i32* %error_code) #21 {
.entry:
  %0 = getelementptr i8*, i8** %byte_stream, i32 0
  %1 = load i8*, i8** %0
  %2 = getelementptr i8*, i8** %byte_stream, i32 1
  %3 = load i8*, i8** %2
  %4 = getelementptr i8*, i8** %byte_stream, i32 2
  %5 = load i8*, i8** %4
  %6 = load i64, i64* %row_count_ptr, align 8
  %7 = load i32, i32* %max_matched_ptr, align 4
  %crt_matched = alloca i32
  %old_total_matched = alloca i32
  %8 = call i32 @pos_start_impl(i32* %error_code)
  %9 = call i32 @pos_step_impl()
  %10 = call i32 @group_buff_idx_impl()
  %11 = sext i32 %8 to i64
  %12 = getelementptr i64*, i64** %group_by_buffers, i32 %10
  %13 = load i64*, i64** %12, align 8
  %14 = call i64* @init_shared_mem_nop(i64* %13, i32 0)
  %15 = icmp slt i64 %11, %6
  br i1 %15, label %.loop.preheader, label %.exit

.loop.preheader:                                  ; preds = %.entry
  %16 = sext i32 %9 to i64
  br label %.forbody

.forbody:                                         ; preds = %.forbody, %.loop.preheader
  %pos = phi i64 [ %11, %.loop.preheader ], [ %18, %.forbody ]
  %17 = call i32 @row_func(i64* %14, i64* null, i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off_ptr, i64* %row_count_ptr, i8* %literals, i8* %1, i8* %3, i8* %5, i64* %join_hash_tables)
  %18 = add i64 %pos, %16
  %19 = icmp slt i64 %18, %6
  br i1 %19, label %.forbody, label %._crit_edge

._crit_edge:                                      ; preds = %.forbody
  br label %.exit

.exit:                                            ; preds = %._crit_edge, %.entry
  call void @write_back_nop(i64* %13, i64* %14, i32 0)
  ret void
}

; Function Attrs: alwaysinline
define i32 @row_func(i64* %group_by_buff, i64* %small_group_by_buff, i32* %crt_match, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off, i64* %num_rows_per_scan, i8* %literals, i8* %col_buf0, i8* %col_buf1, i8* %col_buf2, i64* %join_hash_tables) #22 {
entry:
  %0 = load i64, i64* %frag_row_off
  br i1 true, label %filter_true, label %filter_false

filter_true:                                      ; preds = %entry
  %1 = alloca i64, i32 3
  %2 = call i64 @fixed_width_int_decode(i8* %col_buf2, i32 4, i64 %pos)
  %3 = trunc i64 %2 to i32
  %4 = call i64 @translate_null_key_int32_t(i32 %3, i32 -2147483648, i32 351)
  %5 = sext i32 %3 to i64
  %6 = getelementptr i64, i64* %1, i32 0
  store i64 %4, i64* %6
  %7 = call i64 @fixed_width_int_decode(i8* %col_buf1, i32 8, i64 %pos)
  %8 = call i64 @ExtractFromTimeNullable(i32 0, i64 %7, i64 -9223372036854775808)
  %9 = call i64 @translate_null_key_int64_t(i64 %8, i64 -9223372036854775808, i64 2009)
  %10 = getelementptr i64, i64* %1, i32 1
  store i64 %9, i64* %10
  %11 = call i64 @ExtractFromTimeNullable(i32 2, i64 %7, i64 -9223372036854775808)
  %12 = call i64 @translate_null_key_int64_t(i64 %11, i64 -9223372036854775808, i64 13)
  %13 = getelementptr i64, i64* %1, i32 2
  store i64 %12, i64* %13
  %14 = call i32 @perfect_key_hash(i64* %1)
  %15 = call i64* @get_matching_group_value_perfect_hash(i64* %group_by_buff, i32 %14, i64* %1, i32 3, i32 8)
  %16 = getelementptr i64, i64* %15, i32 0
  %17 = sext i32 %3 to i64
  call void @agg_id(i64* %16, i64 %17)
  %18 = getelementptr i64, i64* %15, i32 1
  call void @agg_id(i64* %18, i64 %11)
  %19 = getelementptr i64, i64* %15, i32 2
  call void @agg_id(i64* %19, i64 %8)
  %20 = call i64 @fixed_width_int_decode(i8* %col_buf0, i32 2, i64 %pos)
  %21 = trunc i64 %20 to i16
  %22 = getelementptr i64, i64* %15, i32 3
  %23 = sext i16 %21 to i64
  %24 = call i64 @agg_sum_skip_val(i64* %22, i64 %23, i64 -32768)
  %25 = getelementptr i64, i64* %15, i32 4
  %26 = sext i16 %21 to i64
  %27 = call i64 @agg_count_skip_val(i64* %25, i64 %26, i64 -32768)
  br label %filter_false

filter_false:                                     ; preds = %filter_true, %entry
  ret i32 0
}
```

```
mapdql> explain select dest_name, extract(month from dep_timestamp) as m, extract(year from dep_timestamp) as y,   avg(arrdelay) as del from flights group by dest_name,y,m;
Explanation
IR for the CPU:
===============

; Function Attrs: uwtable
define void @query_group_by_template(i8** nocapture readnone %byte_stream, i8* nocapture readonly %literals, i64* nocapture readnone %row_count_ptr, i64* nocapture readonly %frag_row_off_ptr, i32* %max_matched_ptr, i64* %agg_init_val, i64** %group_by_buffers, i64** %small_groups_buffer, i32 %frag_idx, i64* %join_hash_tables, i32* %total_matched, i32* %error_code) #21 {
.entry:
  %0 = getelementptr i8*, i8** %byte_stream, i32 0
  %1 = load i8*, i8** %0
  %2 = getelementptr i8*, i8** %byte_stream, i32 1
  %3 = load i8*, i8** %2
  %4 = getelementptr i8*, i8** %byte_stream, i32 2
  %5 = load i8*, i8** %4
  %6 = load i64, i64* %row_count_ptr, align 8
  %7 = load i32, i32* %max_matched_ptr, align 4
  %crt_matched = alloca i32
  %old_total_matched = alloca i32
  %8 = call i32 @pos_start_impl(i32* %error_code)
  %9 = call i32 @pos_step_impl()
  %10 = call i32 @group_buff_idx_impl()
  %11 = sext i32 %8 to i64
  %12 = getelementptr i64*, i64** %group_by_buffers, i32 %10
  %13 = load i64*, i64** %12, align 8
  %14 = call i64* @init_shared_mem_nop(i64* %13, i32 0)
  %15 = icmp slt i64 %11, %6
  br i1 %15, label %.loop.preheader, label %.exit

.loop.preheader:                                  ; preds = %.entry
  %16 = sext i32 %9 to i64
  br label %.forbody

.forbody:                                         ; preds = %.forbody, %.loop.preheader
  %pos = phi i64 [ %11, %.loop.preheader ], [ %18, %.forbody ]
  %17 = call i32 @row_func(i64* %14, i64* null, i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off_ptr, i64* %row_count_ptr, i8* %literals, i8* %1, i8* %3, i8* %5, i64* %join_hash_tables)
  %18 = add i64 %pos, %16
  %19 = icmp slt i64 %18, %6
  br i1 %19, label %.forbody, label %._crit_edge

._crit_edge:                                      ; preds = %.forbody
  br label %.exit

.exit:                                            ; preds = %._crit_edge, %.entry
  call void @write_back_nop(i64* %13, i64* %14, i32 0)
  ret void
}

; Function Attrs: alwaysinline
define i32 @row_func(i64* %group_by_buff, i64* %small_group_by_buff, i32* %crt_match, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off, i64* %num_rows_per_scan, i8* %literals, i8* %col_buf0, i8* %col_buf1, i8* %col_buf2, i64* %join_hash_tables) #22 {
entry:
  %0 = load i64, i64* %frag_row_off
  br i1 true, label %filter_true, label %filter_false

filter_true:                                      ; preds = %entry
  %1 = alloca i64, i32 3
  %2 = call i64 @fixed_width_int_decode(i8* %col_buf2, i32 4, i64 %pos)
  %3 = trunc i64 %2 to i32
  %4 = call i64 @translate_null_key_int32_t(i32 %3, i32 -2147483648, i32 351)
  %5 = sext i32 %3 to i64
  %6 = getelementptr i64, i64* %1, i32 0
  store i64 %4, i64* %6
  %7 = call i64 @fixed_width_int_decode(i8* %col_buf1, i32 8, i64 %pos)
  %8 = call i64 @ExtractFromTimeNullable(i32 0, i64 %7, i64 -9223372036854775808)
  %9 = call i64 @translate_null_key_int64_t(i64 %8, i64 -9223372036854775808, i64 2009)
  %10 = getelementptr i64, i64* %1, i32 1
  store i64 %9, i64* %10
  %11 = call i64 @ExtractFromTimeNullable(i32 2, i64 %7, i64 -9223372036854775808)
  %12 = call i64 @translate_null_key_int64_t(i64 %11, i64 -9223372036854775808, i64 13)
  %13 = getelementptr i64, i64* %1, i32 2
  store i64 %12, i64* %13
  %14 = call i32 @perfect_key_hash(i64* %1)
  %15 = call i64* @get_matching_group_value_perfect_hash(i64* %group_by_buff, i32 %14, i64* %1, i32 3, i32 8)
  %16 = getelementptr i64, i64* %15, i32 0
  %17 = sext i32 %3 to i64
  call void @agg_id(i64* %16, i64 %17)
  %18 = getelementptr i64, i64* %15, i32 1
  call void @agg_id(i64* %18, i64 %11)
  %19 = getelementptr i64, i64* %15, i32 2
  call void @agg_id(i64* %19, i64 %8)
  %20 = call i64 @fixed_width_int_decode(i8* %col_buf0, i32 2, i64 %pos)
  %21 = trunc i64 %20 to i16
  %22 = getelementptr i64, i64* %15, i32 3
  %23 = sext i16 %21 to i64
  %24 = call i64 @agg_sum_skip_val(i64* %22, i64 %23, i64 -32768)
  %25 = getelementptr i64, i64* %15, i32 4
  %26 = sext i16 %21 to i64
  %27 = call i64 @agg_count_skip_val(i64* %25, i64 %26, i64 -32768)
  br label %filter_false

filter_false:                                     ; preds = %filter_true, %entry
  ret i32 0
}
```

After testhound patch:

```
mapdql> explain select dest_name, extract(month from dep_timestamp) as m, extract(year from dep_timestamp) as y,   avg(arrdelay) as del from flights group by dest_name,y,m;
Explanation
IR for the CPU:
===============

; Function Attrs: uwtable
define void @query_group_by_template(i8** nocapture readnone %byte_stream, i8* nocapture readonly %literals, i64* nocapture readnone %row_count_ptr, i64* nocapture readonly %frag_row_off_ptr, i32* %max_matched_ptr, i64* %agg_init_val, i64** %group_by_buffers, i64** %small_groups_buffer, i32 %frag_idx, i64* %join_hash_tables, i32* %total_matched, i32* %error_code) #21 {
.entry:
  %0 = getelementptr i8*, i8** %byte_stream, i32 0
  %1 = load i8*, i8** %0
  %2 = getelementptr i8*, i8** %byte_stream, i32 1
  %3 = load i8*, i8** %2
  %4 = getelementptr i8*, i8** %byte_stream, i32 2
  %5 = load i8*, i8** %4
  %6 = load i64, i64* %row_count_ptr, align 8
  %7 = load i32, i32* %max_matched_ptr, align 4
  %crt_matched = alloca i32
  %old_total_matched = alloca i32
  %8 = call i32 @pos_start_impl(i32* %error_code)
  %9 = call i32 @pos_step_impl()
  %10 = call i32 @group_buff_idx_impl()
  %11 = sext i32 %8 to i64
  %12 = getelementptr i64*, i64** %group_by_buffers, i32 %10
  %13 = load i64*, i64** %12, align 8
  %14 = call i64* @init_shared_mem_nop(i64* %13, i32 0)
  %15 = icmp slt i64 %11, %6
  br i1 %15, label %.loop.preheader, label %.exit

.loop.preheader:                                  ; preds = %.entry
  %16 = sext i32 %9 to i64
  br label %.forbody

.forbody:                                         ; preds = %.forbody, %.loop.preheader
  %pos = phi i64 [ %11, %.loop.preheader ], [ %18, %.forbody ]
  %17 = call i32 @row_func(i64* %14, i64* null, i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off_ptr, i64* %row_count_ptr, i8* %literals, i8* %1, i8* %3, i8* %5, i64* %join_hash_tables)
  %18 = add i64 %pos, %16
  %19 = icmp slt i64 %18, %6
  br i1 %19, label %.forbody, label %._crit_edge

._crit_edge:                                      ; preds = %.forbody
  br label %.exit

.exit:                                            ; preds = %._crit_edge, %.entry
  call void @write_back_nop(i64* %13, i64* %14, i32 0)
  ret void
}

; Function Attrs: alwaysinline
define i32 @row_func(i64* %group_by_buff, i64* %small_group_by_buff, i32* %crt_match, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off, i64* %num_rows_per_scan, i8* %literals, i8* %col_buf0, i8* %col_buf1, i8* %col_buf2, i64* %join_hash_tables) #22 {
entry:
  %0 = load i64, i64* %frag_row_off
  br i1 true, label %filter_true, label %filter_false

filter_true:                                      ; preds = %entry
  %1 = alloca i64, i32 3
  %2 = call i64 @fixed_width_int_decode(i8* %col_buf2, i32 4, i64 %pos)
  %3 = trunc i64 %2 to i32
  %4 = call i64 @translate_null_key_int32_t(i32 %3, i32 -2147483648, i32 351)
  %5 = sext i32 %3 to i64
  %6 = getelementptr i64, i64* %1, i32 0
  store i64 %4, i64* %6
  %7 = call i64 @fixed_width_int_decode(i8* %col_buf1, i32 8, i64 %pos)
  %8 = call i64 @extract_year_nullable(i64 %7, i64 -9223372036854775808)
  %9 = call i64 @translate_null_key_int64_t(i64 %8, i64 -9223372036854775808, i64 2009)
  %10 = getelementptr i64, i64* %1, i32 1
  store i64 %9, i64* %10
  %11 = call i64 @extract_month_nullable(i64 %7, i64 -9223372036854775808)
  %12 = call i64 @translate_null_key_int64_t(i64 %11, i64 -9223372036854775808, i64 13)
  %13 = getelementptr i64, i64* %1, i32 2
  store i64 %12, i64* %13
  %14 = call i32 @perfect_key_hash(i64* %1)
  %15 = call i64* @get_matching_group_value_perfect_hash(i64* %group_by_buff, i32 %14, i64* %1, i32 3, i32 8)
  %16 = getelementptr i64, i64* %15, i32 0
  %17 = sext i32 %3 to i64
  call void @agg_id(i64* %16, i64 %17)
  %18 = getelementptr i64, i64* %15, i32 1
  call void @agg_id(i64* %18, i64 %11)
  %19 = getelementptr i64, i64* %15, i32 2
  call void @agg_id(i64* %19, i64 %8)
  %20 = call i64 @fixed_width_int_decode(i8* %col_buf0, i32 2, i64 %pos)
  %21 = trunc i64 %20 to i16
  %22 = getelementptr i64, i64* %15, i32 3
  %23 = sext i16 %21 to i64
  %24 = call i64 @agg_sum_skip_val(i64* %22, i64 %23, i64 -32768)
  %25 = getelementptr i64, i64* %15, i32 4
  %26 = sext i16 %21 to i64
  %27 = call i64 @agg_count_skip_val(i64* %25, i64 %26, i64 -32768)
  br label %filter_false

filter_false:                                     ; preds = %filter_true, %entry
  ret i32 0
}
```
```
mapdql> explain select dest_name, extract(month from dep_timestamp) as m, extract(year from dep_timestamp) as y,   avg(arrdelay) as del from flights group by dest_name,y,m;
Explanation
IR for the CPU:
===============

; Function Attrs: uwtable
define void @query_group_by_template(i8** nocapture readnone %byte_stream, i8* nocapture readonly %literals, i64* nocapture readnone %row_count_ptr, i64* nocapture readonly %frag_row_off_ptr, i32* %max_matched_ptr, i64* %agg_init_val, i64** %group_by_buffers, i64** %small_groups_buffer, i32 %frag_idx, i64* %join_hash_tables, i32* %total_matched, i32* %error_code) #21 {
.entry:
  %0 = getelementptr i8*, i8** %byte_stream, i32 0
  %1 = load i8*, i8** %0
  %2 = getelementptr i8*, i8** %byte_stream, i32 1
  %3 = load i8*, i8** %2
  %4 = getelementptr i8*, i8** %byte_stream, i32 2
  %5 = load i8*, i8** %4
  %6 = load i64, i64* %row_count_ptr, align 8
  %7 = load i32, i32* %max_matched_ptr, align 4
  %crt_matched = alloca i32
  %old_total_matched = alloca i32
  %8 = call i32 @pos_start_impl(i32* %error_code)
  %9 = call i32 @pos_step_impl()
  %10 = call i32 @group_buff_idx_impl()
  %11 = sext i32 %8 to i64
  %12 = getelementptr i64*, i64** %group_by_buffers, i32 %10
  %13 = load i64*, i64** %12, align 8
  %14 = call i64* @init_shared_mem_nop(i64* %13, i32 0)
  %15 = icmp slt i64 %11, %6
  br i1 %15, label %.loop.preheader, label %.exit

.loop.preheader:                                  ; preds = %.entry
  %16 = sext i32 %9 to i64
  br label %.forbody

.forbody:                                         ; preds = %.forbody, %.loop.preheader
  %pos = phi i64 [ %11, %.loop.preheader ], [ %18, %.forbody ]
  %17 = call i32 @row_func(i64* %14, i64* null, i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off_ptr, i64* %row_count_ptr, i8* %literals, i8* %1, i8* %3, i8* %5, i64* %join_hash_tables)
  %18 = add i64 %pos, %16
  %19 = icmp slt i64 %18, %6
  br i1 %19, label %.forbody, label %._crit_edge

._crit_edge:                                      ; preds = %.forbody
  br label %.exit

.exit:                                            ; preds = %._crit_edge, %.entry
  call void @write_back_nop(i64* %13, i64* %14, i32 0)
  ret void
}

; Function Attrs: alwaysinline
define i32 @row_func(i64* %group_by_buff, i64* %small_group_by_buff, i32* %crt_match, i32* %total_matched, i32* %old_total_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off, i64* %num_rows_per_scan, i8* %literals, i8* %col_buf0, i8* %col_buf1, i8* %col_buf2, i64* %join_hash_tables) #22 {
entry:
  %0 = load i64, i64* %frag_row_off
  br i1 true, label %filter_true, label %filter_false

filter_true:                                      ; preds = %entry
  %1 = alloca i64, i32 3
  %2 = call i64 @fixed_width_int_decode(i8* %col_buf2, i32 4, i64 %pos)
  %3 = trunc i64 %2 to i32
  %4 = call i64 @translate_null_key_int32_t(i32 %3, i32 -2147483648, i32 351)
  %5 = sext i32 %3 to i64
  %6 = getelementptr i64, i64* %1, i32 0
  store i64 %4, i64* %6
  %7 = call i64 @fixed_width_int_decode(i8* %col_buf1, i32 8, i64 %pos)
  %8 = call i64 @extract_year_nullable(i64 %7, i64 -9223372036854775808)
  %9 = call i64 @translate_null_key_int64_t(i64 %8, i64 -9223372036854775808, i64 2009)
  %10 = getelementptr i64, i64* %1, i32 1
  store i64 %9, i64* %10
  %11 = call i64 @extract_month_nullable(i64 %7, i64 -9223372036854775808)
  %12 = call i64 @translate_null_key_int64_t(i64 %11, i64 -9223372036854775808, i64 13)
  %13 = getelementptr i64, i64* %1, i32 2
  store i64 %12, i64* %13
  %14 = call i32 @perfect_key_hash(i64* %1)
  %15 = call i64* @get_matching_group_value_perfect_hash(i64* %group_by_buff, i32 %14, i64* %1, i32 3, i32 8)
  %16 = getelementptr i64, i64* %15, i32 0
  %17 = sext i32 %3 to i64
  call void @agg_id(i64* %16, i64 %17)
  %18 = getelementptr i64, i64* %15, i32 1
  call void @agg_id(i64* %18, i64 %11)
  %19 = getelementptr i64, i64* %15, i32 2
  call void @agg_id(i64* %19, i64 %8)
  %20 = call i64 @fixed_width_int_decode(i8* %col_buf0, i32 2, i64 %pos)
  %21 = trunc i64 %20 to i16
  %22 = getelementptr i64, i64* %15, i32 3
  %23 = sext i16 %21 to i64
  %24 = call i64 @agg_sum_skip_val(i64* %22, i64 %23, i64 -32768)
  %25 = getelementptr i64, i64* %15, i32 4
  %26 = sext i16 %21 to i64
  %27 = call i64 @agg_count_skip_val(i64* %25, i64 %26, i64 -32768)
  br label %filter_false

filter_false:                                     ; preds = %filter_true, %entry
  ret i32 0
}
```

**Comment by wamsiv** [comment]
Changes look good, and there is an improvement in performance.

**Comment by randyzwitch** [comment]
@wamsiv or @testhound what's the status of this? The PR now has merge conflicts, feels like we should either fix the conflicts and plan to merge or close (as oppose to leaving the code to rot)

**Comment by testhound** [comment]
Hi Randy,

I asked about the code when I started and the feedback was that it did not improve performance. Based on this my suggestion is that we close the PR.

Michael Collison

**Pull request closed without merging**
